In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Práctica 1 Python y Numpy

In [3]:
4 % 3 # Es 4 mod 3, es decir el resto de la división entera.

1

In [5]:
np.set_printoptions(precision=2, suppress=True)
v = np.array ([1,2,np.e,7])
w = np.array ([1.2 , np.pi, 4, 5])
for expr in ["v", "w", "v + w", "v ** 2", "v % 2", "np.sum(v)", "np.sqrt(w)", "v > 3", "w < 3.5"]:
    print(f"{expr :11s} == {eval(expr)}") # f inicializa una f-string, luego se pone {} para indicar donde va la variable.
                                          # :11 indica la cantidad de caracteres que va a ocupar este string, si son menos se llena con espacios.
                                          # s es para indicar que quiero un string v y no su valor o algo diferente.
                                          # eval es para indicar que quiero el valor de la variable, y no su formato string.

v           == [1.   2.   2.72 7.  ]
w           == [1.2  3.14 4.   5.  ]
v + w       == [ 2.2   5.14  6.72 12.  ]
v ** 2      == [ 1.    4.    7.39 49.  ]
v % 2       == [1.   0.   0.72 1.  ]
np.sum(v)   == 12.718281828459045
np.sqrt(w)  == [1.1  1.77 2.   2.24]
v > 3       == [False False False  True]
w < 3.5     == [ True  True False False]


In [10]:
~(v > 3) # "alt gr" + "+" del teclado NO númerico

array([ True,  True,  True, False])

In [21]:
v = np.array ([1 , 2, np.e, 7])
w = np.array ([1.2 , np.pi, 4, 5])
z = np.array ([0 ,1])
v * w # Multiplicación coord a coord, sin importar shapes
#v+2 # Coord a coord
#v+z # Funcionara? Rta: No lo hace, no dan las shapes

array([ 1.2 ,  6.28, 10.87, 35.  ])

In [28]:
v = np.array ([1, 2, np.e, 7, 5])
# display(v[0], v[1], v[-1], v[-2]) # Funcionara ‘v[-2]‘? Rta: Si
# v[[0, 3]] # Desde el elem 0 hasta el 3 sin incluir
display(v[0:3] , v[0:1]) # Idem anterior

array([1.  , 2.  , 2.72])

array([1.])

In [37]:
a = np.sqrt (2)
display(a)
#np.round(a) # Redondea a enteros
#np.round(a, 2) # Redondea a enteros, y dos decimales
#np.info(np.round)
#np.info(np.ceil) # Ceil = techo, da la parte entera superior
np.ceil(a)

1.4142135623730951

2.0

In [38]:
v = np.array ([a, a**2, a**3, a**(.5) ])
np.floor(v) # Floor = piso, da la parte entera inferior

array([1., 2., 2., 1.])

In [43]:
#np.max(v)  # Valor máximo
#np.min(v)  # Valor mínimo
#np.sum(v)  # Suma todos los valores
#np.mean(v) # Promedio
np.sort(v)  # Ordena el array de menor a mayor

array([1.19, 1.41, 2.  , 2.83])